import time

from google import genai
from google.genai import types

from backend.config import get_settings


class GeminiDocumentGenerator:

    def __init__(self):
        self.settings = get_settings()
        self.client = None

        if self.settings.GEMINI_API_KEY:
            self.client = genai.Client(
                api_key=self.settings.GEMINI_API_KEY
            )

    def generate_document(self, request):

        if not self.client:
            return self.local_fallback(request)

        prompt = f"""
Create a professional first draft of this legal document.

Document Type:
{request.document_type}

Parties:
{request.parties}

Effective Date:
{request.effective_date}

Terms and Conditions:
{request.terms}

Include:
- Title
- Parties
- Effective date
- Purpose
- Services or obligations
- Payment
- Confidentiality
- Intellectual property
- Termination
- Governing law placeholder
- Signature sections
- AI-assisted draft disclaimer

Return only the document.
"""

        try:
            response = self.client.models.generate_content(
                model=self.settings.GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.2,
                    max_output_tokens=4000,
                ),
            )

            if response and response.text:
                return response.text.strip()

        except Exception:
            pass

        return self.local_fallback(request)

    def local_fallback(self, request):

        return f"""
{request.document_type.upper()}

PARTIES

{request.parties}

EFFECTIVE DATE

This agreement becomes effective on {request.effective_date}.

1. PURPOSE

This agreement establishes the terms and conditions between the parties.

2. SERVICES AND OBLIGATIONS

The parties agree to perform their respective responsibilities according
to the agreed specifications and requirements.

3. PAYMENT

Payment shall be made according to the terms agreed between the parties.

4. CONFIDENTIALITY

Both parties shall maintain the confidentiality of non-public information
received from the other party.

5. INTELLECTUAL PROPERTY

Intellectual-property rights shall be handled according to the agreement
between the parties and applicable payment conditions.

6. TERMINATION

Either party may terminate this agreement according to the agreed notice
period and termination conditions.

7. GOVERNING LAW

This agreement shall be governed by:

[GOVERNING LAW]

8. TERMS AND CONDITIONS

{request.terms}

9. SIGNATURES

PARTY 1

Name: ______________________________

Signature: __________________________

Date: ______________________________


PARTY 2

Name: ______________________________

Signature: __________________________

Date: ______________________________


DRAFT FOR REVIEW - NOT LEGAL ADVICE

This document is an AI-assisted first draft generated by LegalEase.
It should be reviewed by a qualified legal professional before use.
""".strip()